import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "../../../../lib/admin-supabase";
import { getOpsIdentity } from "../../../../lib/api-guard";

export async function POST(request: NextRequest) {
  // 1. Security Check (FIX: Removed 'request' argument to pass build)
  const identity = await getOpsIdentity(); 
  
  if (!identity) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  const supabase = createAdminClient();
  const now = new Date().toISOString();

  // 2. Update Profile & Finalize Smart ID Activation
  const { data: updatedProfile, error: opError } = await supabase
    .from("operators")
    .update({
      must_change_password: false,
      password_changed_at: now,
      status: 'active', // User is now officially part of the fleet
      updated_at: now
    })
    .eq("id", identity.id)
    .select('display_id') // This is the H-SADM-0001 format generated by the DB Trigger
    .single();

  if (opError) {
    return NextResponse.json({ error: opError.message }, { status: 500 });
  }

  // 3. Return the Success State
  return NextResponse.json({
    ok: true,
    mustChangePassword: false,
    displayId: updatedProfile.display_id, // Returning the ID for the "Success" UI
    changedAt: now
  });
}